### ISSUE TITLE
Add connect timeout and read timeout parameters to Builder

### ISSUE THREAD

**Issue by jlorentson** [imsweb/naaccr-geocoder-client#10]
Allow the user to specify connectTimeout and readTimeout on the OkHttpClient.

**Comment by jlorentson** [comment]
@ctmay4 GeocoderTest.testBuilder() is timing out when I run it locally. If I comment out the lines 
`.proxyHost(null)
                .proxyPort(null)`
it passes. The same thing happens on master, without these changes. Am I missing something?

**Comment by ctmay4** [comment]
You are behind a firewall so I would have thought you needed the proxy.  The Travis build passed.  Did you comment it out for that build?

**Comment by jlorentson** [comment]
That makes sense. The version I pushed was not commented out, so if it works, it works.

I'm not sure what to do to test these new changes,

**Comment by ctmay4** [comment]
Create a merge request.  I can download and test as well.

**Comment by ctmay4** [comment]
This was merged in #11
