### ISSUE TITLE
Add support for version 4.03

### ISSUE THREAD

**Issue by criderp** [imsweb/naaccr-geocoder-client#15]
Version 4.03 of the geocoder is available on their development site. Here is an example call:

http://naaccr-geo-dev.geoservices.tamu.edu/Services/Geocode/WebService/GeocoderWebServiceHttpNonParsed_V04_03.aspx?streetAddress=9355%20Burton%20Way&city=Beverly%20Hills&state=ca&zip=90210&apikey=ea3783cb-b5a2-4d87-89f1-99366fe19cea&format=XML&census=false&notStore=false&version=4.03&ShouldDoExhaustiveSearch=true

There is a new return value "MicroMatchStatus". Looks like it's the last column in the TSV output.

There is also a new parameter "ShouldDoExhaustiveSearch", which is a boolean parameter.

**Comment by jlorentson** [comment]
@criderp  Is there documentation on the new return value and parameter? I don't see anything about 4.03 on the naaccr.org or tamu.edu pages. As I'm looking at this, it is behaving quite a bit differently than the 4.02 version.

**Comment by criderp** [comment]
The documentation should be on http://naaccr-geo-dev.geoservices.tamu.edu, but I can't get to it because of their odd login behavior. Which part is behaving differently?

**Comment by jlorentson** [comment]
An example is GeocoderTest.testCallWithoutCensus(); if I change the URL and version number (but not that test method), it now returns a bad result with status code = 500 (Failure). If I add the line `input.setShouldDoExhaustiveSearch(false);` it's the same. If I change it to `input.setShouldDoExhaustiveSearch(true);` then the geocoder returns a list of 8 results where before it had been only one.

**Comment by jlorentson** [comment]
It looks like `GeocoderTest.testCallWithoutCensus()` is similar; either 1 bad result if the value of `getShouldDoExhaustiveSearch()` is false or null, 8 results when true. 

I am pretty sure (though I have no record) that most of these tests were passing yesterday with only url and version Asserts changed; could they still be making changes?

**Comment by criderp** [comment]
I agree, I think there is something wrong. I will send them an email.

I did realize I forgot give a basic explanation of what "ShouldDoExhaustiveSearch=true" does. The geocoder has many different data sources that it searches. Normally, it will stop after finding a match in one of the data sources, but the "ShouldDoExhaustiveSearch=true" parameter tells it to search all sources and return all matches.

The "MicroMatchStatus" will indicate if the geocoder thinks the results should be reviewed by a human. I'm not sure what the possible values will be, but we should just treat it as a string.

**Comment by criderp** [comment]
This should be fixed now.

**Comment by jlorentson** [comment]
Most of the tests are working better but the address (123 main street los angeles ca 90007) we use for `testCallWithMultipleResults()` returns only one result. This is with ties allowed, tiebreaking strategy = revert-to-hierarchy, no min score (v4.02 returns a list of 5 results with these parameters). That seems wrong to me, unless the ShouldDoExhaustiveSearch parameter is necessary for multiple results in the new version.

**Comment by ctmay4** [comment]
I'm going to be out of the office next week.  If you need to release the library, @depryf should be able to help.  Fabian, the auto-release mechanism is already in place in Teamcity.  Just verify the version in build.gradle.

**Comment by criderp** [comment]
I looked into this example, and it does seem like a bug. So I will send them an email.

**Comment by criderp** [comment]
The geocoder team is working on this problem. If you have all the changes implemented, we can just sit on this until they fix it.

**Comment by jlorentson** [comment]
There are still a few changes I have to make; I'll work on getting them ready for when you hear back from them.

**Comment by jlorentson** [comment]
@criderp It looks like they added a new option that includes advanced parameters: attribute relaxation, substring matching, soundex, which feature matching hierarchy to use, which reference data sources to use. I assume we want to add support for these. How should we treat the default values? For example, attribute relaxation defaults to true, and ratts (the attributes-to-be-relaxed parameter) defaults to pre,suffix,post,city,zip. Presumably most users won't specify these new parameters; should we assume they "should" be true? 

Documentaion is here: https://geo.naaccr.org/Services/Geocode/WebService/GeocoderWebServiceDetailed.aspx

**Comment by criderp** [comment]
Those were there before, we just never needed them. I wouldn't worry about adding them now (maybe in the future). If we did add them, though, the default should be to not specify the parameter at all. That way the geocoder would use it's own default.

**Comment by jlorentson** [comment]
Ah. Well, I've already added them, so I suppose I'll just leave them in. 

PO Box address is still coming back "unmatchable." From their examples:
https://geo.naaccr.org/Services/Geocode/WebService/GeocoderWebServiceHttpNonParsedDetailed_V04_03.aspx?streetAddress=PO%20Box%20221&city=Beverly%20Hills&state=ca&zip=90210&apikey=905347a9-9336-4b7c-bd6d-3c4670998793&format=xml&census=true&censusYear=2010&notStore=false&verbose=true&geom=true&version=4.03

Oddly, their xml result says Status Code = 200, whereas in our code it returns 500, but in both cases there is no meaningful information returned.

**Comment by criderp** [comment]
Yeah,  you can leave them in. Just make sure the parameters are not included by default. We shouldn't specify the default. If they change the default on their end, we would want that changed applied automatically on our end also.

I sent Payton an email about this problem.

**Comment by jlorentson** [comment]
Ok, I can set the minScore to 59 in the testPoBoxWithCensus() test and it passes. One more problem I am seeing is with the geometry option. It does not seem to be returning the geometry anymore; again, from their example page:
https://geo.naaccr.org/Services/Geocode/WebService/GeocoderWebServiceHttpNonParsedDetailed_V04_03.aspx?streetAddress=9355%20Burton%20Way&city=Beverly%20Hills&state=ca&zip=90210&apikey=905347a9-9336-4b7c-bd6d-3c4670998793&format=xml&census=true&censusYear=2010&notStore=false&verbose=true&geom=true&version=4.03

The Geometry tag is empty even though geom=true is specified. Our test uses the PO Box address, but also doesn't get geometry.

**Comment by criderp** [comment]
Do we know that it worked before? Did we have a unit test for it? Either way I'm not sure it matters, since DMS doesn't use that parameter.

**Comment by jlorentson** [comment]
We did have a unit test that passed and is now failing. 

It looks like it passes if the "detailed" version is used (URL contains "GeocoderWebServiceHttpNonParsedDetailed_V04_03.aspx") but not the "advanced" (URL contains "GeocoderWebServiceHttpNonParsedAdvanced_V04_03.aspx"). 

Which do we care more about - using advanced version (with the parameters from the comment above) or having the geometry returned? DMS uses neither, I believe...

**Comment by criderp** [comment]
We used "detailed" before, didn't we? Let's stick with that one.
