### ISSUE TITLE
Fix MicroMatchStatus bug

### ISSUE THREAD

**Issue by jlorentson** [imsweb/naaccr-geocoder-client#17]
There is a bug in the geocoder client related to the micro match status and exhaustive search results.  Only the first result has the micro match status, so for the other results the client is setting the value to the previous column because of this line:

`result.setMicroMatchStatus(value(parts[parts.length-1]));`

Here is an example URL for testing:

https://geo.naaccr.org/Services/Geocode/WebService/GeocoderWebServiceHttpNonParsedDetailed_V04_03.aspx?zip=20705&notStore=true&streetAddress=3901%20Calverton%20Blvd&city=Calverton&census=true&format=tsv&state=MD&censusYear=1990%7C2000%7C2010&shouldDoExhaustiveSearch=true&version=4.03&verbose=true&apiKey=905347a9-9336-4b7c-bd6d-3c4670998793

 It has a very minor impact in DMS, at least for now, but it should still be fixed.

**Comment by jlorentson** [comment]
@criderp We still want to set the microMatchStatus on each GeocodeOutput object in the list, right? Just get it from the first line for all of them.

**Comment by criderp** [comment]
We should just put the value that is returned by the geocoder for each result.  For the exhaustive search I think that will always be blank after the result.

The problem is that `parts[parts.length-1]` is not safe because the geocoder doesn't return a consistent number of columns. Does that make sense?

**Comment by criderp** [comment]
More specifically, the geocoder doesn't include trailing blank columns.

**Comment by jlorentson** [comment]
If I'm understanding correctly, the first line of the response will always (?) have a value for Micro Match Status as the last column, but subsequent lines will not have a value or even a blank column. Is that correct or am I missing something?

**Comment by criderp** [comment]
I'll never use the word "always" when talking about the geocoder! The only thing we can assume is the column index where the micro match status is supposed to be. If that column doesn't exist, then it should be blank. There shouldn't be any logic related to which result it is.

**Comment by jlorentson** [comment]
The census results are optional, right? My impression was that it does not return a bunch of blank columns if census=false, or if censusYear=2000, etc. Since the Micro Match Status comes after the census information, we don't know which column it will be in. But again, I may be missing something.

**Comment by criderp** [comment]
I did some testing so I could understand exactly what the geocoder is doing.

If census=false OR censusYear is blank, then there are 117 columns. Otherwise, there are 150 columns. So, if only census 2000 is requested, the 1990 and 2010 columns are still included, but they are blank. I think we have to assume that is always true. Still need to handle the fact that trailing blank columns are trimmed, though.

**Comment by ctmay4** [comment]
Does this need to be included in this release?  We need to do a release today.

**Comment by jlorentson** [comment]
I am fine with releasing what we have and releasing this at a later time.

**Comment by criderp** [comment]
I'm fine with that, too. This is getting too complicated for a quick release.

**Comment by ctmay4** [comment]
Ok, I will release now.  We can do another when you guys finish this issue.

**Comment by jlorentson** [comment]
@criderp wrote:
> If census=false OR censusYear is blank, then there are 117 columns. Otherwise, there are 150 columns. So, if only census 2000 is requested, the 1990 and 2010 columns are still included, but they are blank.

I don't think this is true anymore. If I request "9355 Burton Way Beverly Hills CA 90210," which is their sample address, it returns three results. Set census=false and the line lengths are {117, 116, 116}, which makes sense (only the first result has microMatchStatus). 
If I put census=true and no year (i.e., default to allAvailable), the lengths are {150, 149, 149}, which also makes sense.
If I set the year to 1990, the lengths are {150, 127, 127}; the first line has all three years (with two blank-filled) plus microMatchStatus, and the next two have only one census result, no mMS.
If I set the year to 2010, the lengths are {150, 149, 149}; the first line has all three years (with two blank-filled) plus microMatchStatus, and the next two have only one census result, no mMS.
If I set the year to 2000, the lengths are {150, 138, 138}; the first line has all three years (with two blank-filled) plus microMatchStatus, and the next two have two census result, one blank-filled, no mMS.

All of that is handled fine by our code, with the exception of the microMatchStatus bug described above.
But if I set the year to 1990|2000, it gets weird. The lengths are {161, 149, 149}. The first result has four census results: 1990, blank, 2000, blank; plus microMatchStatus. The next two have three: 1990, blank, 2000; no mMS. 
If I set the year to 1990|2010, the lengths are {161, 160, 160}. There are four census: 1990, blank, blank, 2010. Year 2010|1990 gives the same except the order is: blank, 1990, blank, 2010.
These situations would not be handled correctly by our code. I also point out that it goes against their documentation and seems like a bug. I don't think this affects DMS, because we either request all years or just 2010, and both of those are handled fine. But if we want to make this available to other users or we want to request different years in the future, it will not work correctly. I'm not sure how to fix it; there doesn't seem to be a pattern to the weird behavior and I wouldn't be terribly confident in ad-hoc-ing it based on trial and error. One solution would be to change the library to only support (all years or 2010) for the time being.

**Comment by criderp** [comment]
What a mess. After reading your comment I realized my way of checking the number of columns was bad (I was using excel).

I think the solution of only supporting either all years or 2010 only would work. Requesting a single year is really only a performance optimization. It's easy to ignore data that isn't needed.

**Comment by jlorentson** [comment]
I made that change and fixed the MicroMatchStatus bug, as long as those length assumptions remain true. I wonder if we should add a test for that condition. I guess it wouldn't be a unit test per se, since it isn't testing our logic, but more like a canary so that we discover quickly if the format changes. What do you think?

**Comment by criderp** [comment]
I think that test is a great idea.  You are working with Chuck on tests that are run regularly, right?  That should be one of them.

**Comment by jlorentson** [comment]
Yes, I'm going to be making the tests as exhaustive as possible and we will soon start running them on a schedule. That's why I wanted to get this issue buttoned up; so the tests can test the behavior we want, not the behavior we had! 

I'm closing this issue since merge request #22 addressed it.
