### ISSUE TITLE
Set up scheduled testing

### ISSUE THREAD

**Issue by jlorentson** [imsweb/naaccr-geocoder-client#21]
We want to make sure that we know about any changes in the behavior of the AGGIE service. We can begin with running our unit tests nightly but will need to add some integration testing as well. Some of our other modules run scheduled tests through TeamCity; we can set that up for this module as well.

**Comment by ctmay4** [comment]
Don't worry about the scheduling.   That is handled in Teamcity.  We just need to add new sets of unit tests to get better coverage.  If the tests become too slow, we can add them to a new category which are only run as integration tests.
