### ISSUE TITLE
Add support for Version 4.04

### ISSUE THREAD

**Issue by jlorentson** [imsweb/naaccr-geocoder-client#25]
Version 4.04 of the geocoder is available on the dev site.  It has a new field at the end called “PenaltyCode”.  The dashes and numbers have meaning, but I don’t think we need to worry about that right now.  Just need to support the running the new version and storing the new field in the JSON.

**Comment by criderp** [comment]
They replaced the dashes with "M"s and added a second new field called "PenaltyCodeSummary". Both new fields are related to "MicroMatchStatus", so they are also only included on the first result. Here is a sample URL (just add the API key):

https://naaccr-geo-dev.geoservices.tamu.edu/Services/Geocode/WebService/GeocoderWebServiceHttpNonParsedDetailed_V04_04.aspx?zip=20705&notStore=true&streetAddress=3901%20Calverton%20Blvd&city=Calverton&census=true&format=tsv&state=MD&censusYear=1990|2000|2010&shouldDoExhaustiveSearch=true&version=4.04&verbose=true&apiKey=

**Comment by jlorentson** [comment]
The tamu team probably made changes to their weighting algorithm, etc., in the new version, right? All of the unit tests are failing when run with the new url...

**Comment by criderp** [comment]
Probably, but you can give me an example of one that is failing? I just want to make sure it seems like a reasonable change.

**Comment by jlorentson** [comment]
`GeocoderTest.testShouldDoExhaustiveSearch()` searches for "123 main street los angeles ca 90007" and used to return 11 results with `input.setShouldDoExhaustiveSearch(Boolean.FALSE)` and 13 results with `input.setShouldDoExhaustiveSearch(Boolean.TRUE)`; now it is 13 and 15. (It looks like the new results are the first two.)

`GeocoderTest.testResponseLength()` searches for "9355 Burton Way Beverly Hills CA 90210" and used to return 1 result if ties aren't allowed and 3 results if ties are allowed; now it's 1 result either way. It's not clear if that's due to fiddling with the scoring; if I set min score to "1" it still returns only 1 result.

**Comment by jlorentson** [comment]
Another odd one is `GeocoderTest.testCallWithMultipleResults()`: the first test that method runs is to set `input.setMinScore("100")` and assert that the result doesn't contain data. NaaccrGisCoordinateQualityCode used to equal 98, now it's 99; NaaccrGisCoordinateQualityName used to be Unknown, now it's Unmatchable. (I assume there are more discrepancies; that test has hundreds of asserts...)

**Comment by criderp** [comment]
1) I think the 2 new results are from a new data source, so this is OK.

2) This looks like a bug that they fixed. I don't know why it was returning 3 results before, since none of them were ties and the first result is a perfect match!

3) A 99 makes more sense than 98 in that case, but the name does seem wrong. I think it might have been switched with the FeatureMatchingGeographyType field. I check with them about that.

**Comment by jlorentson** [comment]
1. I can add those new results to the test.

For 2, I think (and I'm sure I'm remembering somewhat wrong) that it used to include lower-quality matched if allowTies was on, like Zip Code centroid for example. I agree that seems like an odd meaning of "allowTies."

**Comment by jlorentson** [comment]
Waiting for an answer on number 3 above but the other tests are fixed. 

One more thing about number 2; the two "new" results appear as the first two returned but they have a lower match score (63 vs 89) than the subsequent results. Seems wrong, right?

**Comment by criderp** [comment]
Payton said he's looking into #3.

It's correct for those results to be returned first, assuming their data source is the best (which is decided by the geocoder team). The results are always ordered by the quality of the data source, rather than the quality of the match.

**Comment by criderp** [comment]
3. I've been told this was a bug before that is fixed now, so I guess the unit test just needs to be updated. Let me know if there are more changes than just NaaccrGisCoordinateQualityCode, NaaccrGisCoordinateQualityName, and FeatureMatchingGeographyType.

**Comment by criderp** [comment]
I should clarify my comment. It is a bug in the production geocoder, the development geocoder is correct.

**Comment by ctmay4** [comment]
#26 was merged.

**Comment by ctmay4** [comment]
@criderp @jlorentson Can either of you supply me with release notes I can use for this change?

**Comment by criderp** [comment]
Added support for version 4.04, including the "PenaltyCode" and "PenaltyCodeSummary" return values.

**Comment by ctmay4** [comment]
I just released to Maven Central.  Should be visible within 30 minutes.
