### ISSUE TITLE
enable uncertainty hierarchy

### ISSUE THREAD

**Issue by jlorentson** [imsweb/naaccr-geocoder-client#37]
Need to switch to the "advanced" url. @criderp should we move to API version 4.05 with these changes as well?

**Comment by criderp** [comment]
Yeah, we should move to 4.05. I didn't realize we had to switch to the advanced URL to be able to use that parameter. Hopefully that won't cause any problems...

**Comment by jlorentson** [comment]
@criderp It looks like , if I switch the URL and version to 4.05, each census result has an additional field, which of course screws up our parsing. I suspect it's a field they are deliberately adding rather than a bug; the api response doesn't match their documentation on the geo.naaccr.org help page, but the "extra" field comes at the end of each census result and is an 11-digit number; for the beverly hills example in the documentation, I see 
1990: 06037700800
2000: 060377008004
2010: 060377008011

**Comment by criderp** [comment]
I forgot about that, sorry. The new field is GeoLocationID, it's a relatively new standard NAACCR item. It should be added to the Census object. Not sure if we will use it in DMS, though.

**Comment by criderp** [comment]
done in #38
