### ISSUE TITLE
Version 5

### ISSUE THREAD

**Issue by jlorentson** [imsweb/naaccr-geocoder-client#39]

**Comment by jlorentson** [comment]
@criderp how do you feel about switching the format we receive from AGGIE from tsv to json?

**Comment by ctmay4** [comment]
I always found TSV a bit hackish so I think it makes sense.

**Comment by criderp** [comment]
Yes, we should definitely switch to JSON.

**Comment by jlorentson** [comment]
Ok. It's definitely more work, but that's fine with me; I think it will mean less work in maintenance down the road.

**Comment by criderp** [comment]
done in #43
