### ISSUE TITLE
Add URL field to GeocodeOutput

### ISSUE THREAD

**Issue by jlorentson** [imsweb/naaccr-geocoder-client#8]
Some users may want to keep track of the URL that resulted in the data returned, so we want to add a field to the GeocodeOutput class that keeps this information.

**Comment by jlorentson** [comment]
The Request class we are using has a field of type okhttp3.HttpUrl, but I am inclined just to use a String in the GeocodeOutput class to decouple it from any particular implementation. Any thoughts?

**Comment by ctmay4** [comment]
Absolutely.  The `GeocodingOutput` should add a String `url` field.

**Comment by jlorentson** [comment]
Talked to Chuck about this; the URL needs to contain the API Key of the user for the geocoder to return results, but 1) the way we do it now does not make it convenient to hang onto that, and 2) it probably shouldn't be stored anyway. @criderp do you have any objection to saving the URL with all parameters except API Key?

**Comment by criderp** [comment]
I don't have any objections. That's actually how I want it to work. If you look at the code in DMS, the URL stored in the statistics does not include the API key. This was done intentionally.
